### ISSUE TITLE
v1.1版本

### ISSUE THREAD

**Issue by clementine189** [clementine189/TCPDemo#1]
用Socket API建立简易TCP服务端
// 1 建立一个socket
// 2 绑定接受客户端连接的端口 bind 
// 3 监听网络端口 listen 
// 4 等待新客户端连接 accept 
// 5 等待客户端请求 recv
// 6 向客户端返回请求的数据send 
//--循环5-6
// 7 关闭socket  closesocket

用Socket API建立简易TCP客户端
// 1 建立一个socket
// 2 连接服务器 connect
// 3 向服务端发送请求 send
// 4 接收服务器返回的数据 recv
//--循环3-4
// 5 关闭socket  closesocket

**Comment by clementineMT** [comment]
....

**Comment by clementine189** [comment]
纯字符串网络消息
优点：处理简易命令方便快捷
缺点：传递大量数据是字符串解析消耗大
企业中的应用方式：JSON、XML、自定义格式的字符数据形式
